Instructions/20487D_MOD01_DEMO.md

instructions for demo1- create new web App in azure portal

module1-demo1

---

Instructions/20487D_MOD05_DEMO.md

This demo requires just instructions.
Do I need to add **Verify that you have an azure account**? or should it be already in the setup guide?

Mod5 demo3

---

Instructions/20487D_MOD05_DEMO.md

Hi Avi, can you please look at this PR and approve it?

Mod5 Demostration number 4

---

Instructions/20487D_MOD05_DEMO.md

Hi Avi,
Please review and approve.
Thanks

mod05 demo number 5

---

Instructions/20487D_MOD05_DEMO.md

Hi Avi,
Here is demo6 for mod05.
Please review and approve it,
Thank you.

mod05 Demo number 6

---

AllFiles/Mod05/Labfiles/Exercise1/Assets/Flight.cs
AllFiles/Mod05/Labfiles/Exercise1/Assets/FlightsController.cs
AllFiles/Mod05/Labfiles/Exercise1/Solution/BlueYonder.Flights.Service/BlueYonder.Flights.Service.csproj
AllFiles/Mod05/Labfiles/Exercise1/Solution/BlueYonder.Flights.Service/Controllers/FlightsController.cs
AllFiles/Mod05/Labfiles/Exercise1/Solution/BlueYonder.Flights.Service/Models/Flight.cs
AllFiles/Mod05/Labfiles/Exercise1/Solution/BlueYonder.Flights.Service/Program.cs
AllFiles/Mod05/Labfiles/Exercise1/Solution/BlueYonder.Flights.Service/Properties/launchSettings.json
AllFiles/Mod05/Labfiles/Exercise1/Solution/BlueYonder.Flights.Service/Startup.cs
AllFiles/Mod05/Labfiles/Exercise1/Solution/BlueYonder.Flights.Service/appsettings.Development.json
AllFiles/Mod05/Labfiles/Exercise1/Solution/BlueYonder.Flights.Service/appsettings.json
Instructions/20487D_MOD05_DEMO.md
Instructions/20487D_MOD05_LAK.md

Hi Avi,
Please review and approve Mo05 lab number 1.
Thank you.

Mod05 lab 1

---

AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/BlueYonder.Flights.Service/BlueYonder.Flights.Service.csproj
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/BlueYonder.Flights.Service/Controllers/FlightsController.cs
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/BlueYonder.Flights.Service/Database/FlightContext.cs
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/BlueYonder.Flights.Service/Models/Flight.cs
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/BlueYonder.Flights.Service/Program.cs
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/BlueYonder.Flights.Service/Properties/PublishProfiles/Azure.pubxml
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/BlueYonder.Flights.Service/Properties/launchSettings.json
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/BlueYonder.Flights.Service/Startup.cs
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/BlueYonder.Flights.Service/appsettings.Development.json
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/BlueYonder.Flights.Service/appsettings.json
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/Setup/azureSql.json
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/Setup/createAzureSQL.ps1
AllFiles/Mod05/Labfiles/Exercise2/Host In Azure/Setup/sqlScript.sql
Instructions/20487D_MOD05_LAK.md

Hi Avi,
Added code and instructions for lab2 in mod 05.
I did the log streaming via PowerShell.
According to this' ive also change Ex2 Task 3 from "Use Visual Studio’s Server Explorer to view the Web App and its log files" to 
Please review and approve,
Thanks

mod05 lab number 2

---

AllFiles/Mod03/DemoFiles/FirstWebApi/Solution/FirstWebApi/Controllers/ValuesController.cs
AllFiles/Mod03/DemoFiles/FirstWebApi/Solution/FirstWebApi/FirstWebApi.csproj
AllFiles/Mod03/DemoFiles/FirstWebApi/Solution/FirstWebApi/Program.cs
AllFiles/Mod03/DemoFiles/FirstWebApi/Solution/FirstWebApi/Properties/launchSettings.json
AllFiles/Mod03/DemoFiles/FirstWebApi/Solution/FirstWebApi/Startup.cs
AllFiles/Mod03/DemoFiles/FirstWebApi/Solution/FirstWebApi/appsettings.Development.json
AllFiles/Mod03/DemoFiles/FirstWebApi/Solution/FirstWebApi/appsettings.json
Instructions/20487D_MOD03_DEMO.md

Mod 3 Demo 1

---

AllFiles/Mod03/LabFiles/Lab2/Solution/BlueYonder.Hotels.Client/BlueYonder.Hotels.Client.csproj
AllFiles/Mod03/LabFiles/Lab2/Solution/BlueYonder.Hotels.Client/Program.cs
AllFiles/Mod03/LabFiles/Lab2/Solution/BlueYonder.Hotels.Service/BlueYonder.Hotels.Service.csproj
AllFiles/Mod03/LabFiles/Lab2/Solution/BlueYonder.Hotels.Service/Controllers/HotelBookingController.cs
AllFiles/Mod03/LabFiles/Lab2/Solution/BlueYonder.Hotels.Service/Program.cs
AllFiles/Mod03/LabFiles/Lab2/Solution/BlueYonder.Hotels.Service/Properties/launchSettings.json
AllFiles/Mod03/LabFiles/Lab2/Solution/BlueYonder.Hotels.Service/Startup.cs
AllFiles/Mod03/LabFiles/Lab2/Solution/BlueYonder.Hotels.Service/appsettings.Development.json
AllFiles/Mod03/LabFiles/Lab2/Solution/BlueYonder.Hotels.Service/appsettings.json
AllFiles/Mod03/LabFiles/Lab2/Solution/Mod3Lab2.sln
AllFiles/Mod03/LabFiles/Lab2/Starter/BlueYonder.Hotels.Client/BlueYonder.Hotels.Client.csproj
AllFiles/Mod03/LabFiles/Lab2/Starter/BlueYonder.Hotels.Client/Program.cs
AllFiles/Mod03/LabFiles/Lab2/Starter/BlueYonder.Hotels.Service/BlueYonder.Hotels.Service.csproj
AllFiles/Mod03/LabFiles/Lab2/Starter/BlueYonder.Hotels.Service/Controllers/HotelBookingController.cs
AllFiles/Mod03/LabFiles/Lab2/Starter/BlueYonder.Hotels.Service/Program.cs
AllFiles/Mod03/LabFiles/Lab2/Starter/BlueYonder.Hotels.Service/Properties/launchSettings.json
AllFiles/Mod03/LabFiles/Lab2/Starter/BlueYonder.Hotels.Service/Startup.cs
AllFiles/Mod03/LabFiles/Lab2/Starter/BlueYonder.Hotels.Service/appsettings.Development.json
AllFiles/Mod03/LabFiles/Lab2/Starter/BlueYonder.Hotels.Service/appsettings.json
AllFiles/Mod03/LabFiles/Lab2/Starter/Mod3Lab2.sln
Instructions/20487D_MOD03_LAK.md

added instructions and starter and solution code

mod 3 Lab 2

---

Instructions/20487D_MOD06_DEMO.md

mod 6 demo 1

---

Instructions/20487D_MOD06_LAK.md

fixed instractions mod06 - LAK (Lab1+Lab2)

fixed instractions mod06 - LAK

---

Instructions/20487D_MOD06_DEMO.md

fixed instructions mod06 - demo

fixed instructions mod06 - demo

---

Instructions/20487D_MOD05_DEMO.md
Instructions/20487D_MOD05_LAK.md

fixed instractions mod05 demo + mod05  lab

fixed instractions mod05 demo + mod05  lab

---

Instructions/20487D_MOD06_LAB_MANUAL.md

adding-mod06-lab-manual

---

Instructions/20487D_MOD01_DEMO.md
Instructions/20487D_MOD01_LAK.md
Instructions/20487D_MOD02_DEMO.md
Instructions/20487D_MOD02_LAK.md
Instructions/20487D_MOD03_DEMO.md
Instructions/20487D_MOD03_LAK.md
Instructions/20487D_MOD04_DEMO.md
Instructions/20487D_MOD04_LAK.md
Instructions/20487D_MOD05_DEMO.md
Instructions/20487D_MOD05_LAK.md
Instructions/20487D_MOD06_DEMO.md
Instructions/20487D_MOD06_LAK.md
Instructions/20487D_MOD07_DEMO.md

updating instructions in all modules

updating instructions in all modules

---

AllFiles/Mod10/Labfiles/Lab1/Starter/Middleware/MachineNameMiddleware.cs
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/BlueYonder.Flights.Service.csproj
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/Controllers/DestinationsController.cs
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/Middleware/MachineNameMiddleware.cs
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/Models/Destination.cs
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/Program.cs
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/Properties/PublishProfiles/Azure.pubxml
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/Properties/PublishProfiles/Azureprofile.xml
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/Properties/launchSettings.json
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/Startup.cs
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/appsettings.Development.json
AllFiles/Mod10/Labfiles/Lab2/Setup/Code/appsettings.json
AllFiles/Mod10/Labfiles/Lab2/Setup/createAzureServicesWestEurope.ps1
AllFiles/Mod10/Labfiles/Lab2/Setup/createAzureServicesWestUS.ps1
AllFiles/Mod10/Labfiles/Lab2/Setup/parameters.json
AllFiles/Mod10/Labfiles/Lab2/Setup/template.json
Instructions/20487D_MOD10_LAK.md
Instructions/20487D_MOD10_LAK_MANUAL.md

Mod10 lab2

---

Instructions/20487D_MOD07_DEMO.md
Instructions/20487D_MOD07_LAK.md

mod07-instruction-fix

---

Instructions/20487D_MOD02_DEMO.md

20487D | Mod02 | Demo

---

Instructions/20487D_MOD02_LAK.md

20487D | Mod02 | LAK

---

Instructions/20487D_MOD03_LAK.md

CE complete. Ready for SME. 
See my comments.

Apposite 20487 d mod03 lak

---

Instructions/20487D_MOD01_LAK.md

Apposite 20487 d mod01 lak

---

Instructions/20487D_MOD01_DEMO.md

Apposite 20487 d mod01 demo

---

Instructions/20487D_MOD03_DEMO.md

Made change to Line 32 as per Avi's comment.

Apposite 20487 d mod03 demo

---

Instructions/20487D_MOD8_DEMO.md

mod08-fixing-instructions

---

Instructions/20487D_MOD01_LAB_MANUAL.md

20487d | Mod01 | LM

---

AllFiles/Mod08/DemoFiles/Mod8Demo6/Solution/BlueYonder.Flights.Service/BlueYonder.Flights.Service.csproj
AllFiles/Mod08/DemoFiles/Mod8Demo6/Solution/BlueYonder.Flights.Service/Controllers/ValuesController.cs
AllFiles/Mod08/DemoFiles/Mod8Demo6/Solution/BlueYonder.Flights.Service/Program.cs
AllFiles/Mod08/DemoFiles/Mod8Demo6/Solution/BlueYonder.Flights.Service/Properties/Azure.pubxml
AllFiles/Mod08/DemoFiles/Mod8Demo6/Solution/BlueYonder.Flights.Service/Properties/Azureprofile.xml
AllFiles/Mod08/DemoFiles/Mod8Demo6/Solution/BlueYonder.Flights.Service/Properties/launchSettings.json
AllFiles/Mod08/DemoFiles/Mod8Demo6/Solution/BlueYonder.Flights.Service/Startup.cs
AllFiles/Mod08/DemoFiles/Mod8Demo6/Solution/BlueYonder.Flights.Service/appsettings.Development.json
AllFiles/Mod08/DemoFiles/Mod8Demo6/Solution/BlueYonder.Flights.Service/appsettings.json
AllFiles/Mod08/DemoFiles/Mod8Demo6/Starter/Setup/createAzureServices.ps1
AllFiles/Mod08/DemoFiles/Mod8Demo6/Starter/Setup/parameters.json
AllFiles/Mod08/DemoFiles/Mod8Demo6/Starter/Setup/template.json
Instructions/20487D_MOD8_DEMO5.md

adding-mod08-demo6

---

Instructions/20487D_MOD04_LAB_MANUAL.md

20487D | Mod04 | LM

---

Instructions/20487D_MOD04_LAK.md

20487D | Mod04 | LAK

---

Instructions/20487D_MOD04_DEMO.md

20487D | Mod04 | Demo

---

Instructions/20487D_MOD05_LAK.md

20487D | Mod05 | LAK | CE complete

---

Instructions/20487D_MOD05_LAB_MANUAL.md

20487D | Mod05 | LM | CE complete

---

Instructions/20487D_MOD03_LAB_MANUAL.md

CE complete. Ready for SME.
Comments inline

20487D | Mod03 | LM

---

Instructions/20487D_MOD06_LAK.md

20487D | Mod06 | LAK

---

Instructions/20487D_MOD06_DEMO.md

20487D | Mod06 | Demo

---

AllFiles/Mod09/DemoFiles/AADB2C/AADB2C.sln
AllFiles/Mod09/DemoFiles/AADB2C/AADB2C/AADB2C.csproj
AllFiles/Mod09/DemoFiles/AADB2C/AADB2C/Controllers/ValuesController.cs
AllFiles/Mod09/DemoFiles/AADB2C/AADB2C/Program.cs
AllFiles/Mod09/DemoFiles/AADB2C/AADB2C/Properties/launchSettings.json
AllFiles/Mod09/DemoFiles/AADB2C/AADB2C/Startup.cs
AllFiles/Mod09/DemoFiles/AADB2C/AADB2C/appsettings.Development.json
AllFiles/Mod09/DemoFiles/AADB2C/AADB2C/appsettings.json
AllFiles/Mod09/DemoFiles/OpenIDConnectAAD/OpenIDConnectAAD.sln
AllFiles/Mod09/DemoFiles/OpenIDConnectAAD/OpenIDConnectAAD/Controllers/ValuesController.cs
AllFiles/Mod09/DemoFiles/OpenIDConnectAAD/OpenIDConnectAAD/OpenIDConnectAAD.csproj
AllFiles/Mod09/DemoFiles/OpenIDConnectAAD/OpenIDConnectAAD/Program.cs
AllFiles/Mod09/DemoFiles/OpenIDConnectAAD/OpenIDConnectAAD/Properties/launchSettings.json
AllFiles/Mod09/DemoFiles/OpenIDConnectAAD/OpenIDConnectAAD/Startup.cs
AllFiles/Mod09/DemoFiles/OpenIDConnectAAD/OpenIDConnectAAD/appsettings.Development.json
AllFiles/Mod09/DemoFiles/OpenIDConnectAAD/OpenIDConnectAAD/appsettings.json
Instructions/20487D_MOD09_DEMO.md

Demo 5 preparation steps is missing

module 9 demo 4 and 5

---

Instructions/20487D_MOD06_LAB_MANUAL.md

20487D | Mod06 | LM

---

Instructions/20487D_MOD09_LAB_MANUAL.md

Apposite 20487 d mod09 lm
